# Generated by Django 4.2.6 on 2023-10-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата оплаты'),
        ),
    ]
